# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build:prod
      env:
        CI: true
    - uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        cp ./dist ./scripts/
        ref=${{ github.ref }}
        docker build scripts -t goadminteam/go-admin-ui:${ref##*/}-${{ github.sha }}
        docker tag goadminteam/go-admin-ui:${ref##*/}-${{ github.sha }} goadminteam/go-admin-ui:latest
        docker push goadminteam/go-admin-ui:${ref##*/}-${{ github.sha }}
        docker push goadminteam/go-admin-ui:latest
